export const majors: string[] = [
    "Astronomy & Astrophysics",
  "Anthropology",
  "Bioengineering",
  "Biology",
  "Black Diaspora and African American Studies",
  "Chemical Engineering",
  "Chemistry",
  "Chinese Studies",
  "Cinematic Arts",
  "Classical Studies",
  "Cognitive Science",
  "Communication",
  "Computer Engineering",
  "Computer Science",
  "Critical Gender Studies",
  "Data Science",
  "Economics",
  "Education Sciences",
  "Electrical Engineering",
  "Engineering Physics",
  "Environmental Systems",
  "Ethnic Studies",
  "German Studies",
  "Global Health",
  "History",
  "Human Developmental Sciences",
  "Individual Studies",
  "International Studies",
  "Italian Studies",
  "Japanese Studies",
  "Jewish Studies",
  "Latin American Studies",
  "Language Studies",
  "Linguistics",
  "Literary Arts",
  "Literatures in English",
  "Mathematics",
  "Mechanical Engineering",
  "Music",
  "Nanoengineering",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Religion",
  "Russian, East European, and Eurasian Studies",
  "Marine Biology",
  "Oceanic and Atmospheric Sciences",
  "Geosciences",
  "Sociology",
  "Structural Engineering",
  "Dance",
  "Theatre",
  "Undeclared",
  "Urban Studies and Planning",
  "Real Estate and Development",
  "Visual Arts",
  "Speculative Design"
]