export const majors: string[] = [
    "Astronomy & Astrophysics (B.S.)",
    "Astronomy & Astrophysics (B.A.)",
    "Anthropology (Concentration in Archaeology)",
    "Anthropology (Concentration in Biological Anthropology)",
    "Anthropology (Concentration in Sociocultural Anthropology)",
    "Anthropology with a Concentration in Climate Change and Human Solutions",
    "Biological Anthropology",
    "Environmental Anthropology",
    "Bioengineering",
    "Bioengineering (Bioinformatics)",
    "Bioengineering: BioSystems",
    "Bioengineering (Biotechnology)",
    "Biology with Specialization in Bioinformatics",
    "Ecology, Behavior, and Evolution",
    "General Biology",
    "Human Biology",
    "Microbiology",
    "Molecular and Cell Biology",
    "Neurobiology",
    "Biochemistry and Cell Biology",
    "Black Diaspora and African American Studies",
    "Chemical Engineering",
    "Biochemistry",
    "Chemistry",
    "Environmental Chemistry",
    "Molecular Synthesis",
    "Pharmacological Chemistry",
    "Chinese Studies",
    "Cinematic Arts",
    "Classical Studies",
    "Cognitive Science",
    "Cognitive and Behavioral Neuroscience",
    "Cognitive Science with a Specialization in Clinical Aspects of Cognition",
    "Cognitive Science with a Specialization in Design and Interaction",
    "Cognitive Science with a Specialization in Language and Culture",
    "Cognitive Science with a Specialization in Machine Learning and Neural Computation",
    "Cognitive Science with a Specialization in Neuroscience",
    "Communication",
    "Media Industries and Communication",
    "Computer Engineering",
    "Computer Science (B.S.)",
    "Computer Science with a Specialization in Bioinformatics",
    "Critical Gender Studies",
    "Data Science",
    "Business Economics",
    "Economics (B.A.)",
    "Economics (B.S.)",
    "Economics-Public Policy (B.A./MPP only)",
    "Joint Major in Mathematics and Economics",
    "Education Sciences",
    "Computer Engineering (ECE)",
    "Electrical Engineering",
    "Engineering Physics",
    "Electrical Engineering & Society (B.A.)",
    "Environmental Systems (Earth Sciences)",
    "Environmental Systems (Ecology, Behavior, and Evolution)",
    "Environmental Systems (Environmental Chemistry)",
    "Environmental Systems (Environmental Policy)",
    "Ethnic Studies",
    "German Studies",
    "Global Health (B.A.)",
    "Global Health (B.S.)",
    "Global South Studies",
    "Public Health",
    "Public Health with Concentration in Biostatistics",
    "Public Health with Concentration in Climate and Environmental Sciences",
    "Public Health with Concentration in Community Health Sciences",
    "Public Health with Concentration in Epidemiology",
    "Public Health with Concentration in Health Policy and Management Sciences",
    "Public Health with Concentration in Medicine Sciences",
    "History",
    "Human Developmental Sciences (B.A.)",
    "Human Developmental Sciences (B.S.)",
    "Human Developmental Sciences with a Specialization in Equity and Diversity",
    "Human Developmental Sciences with a Specialization in Healthy Aging",
    "Eleanor Roosevelt College Individual Studies",
    "Muir College Special Project Major",
    "Revelle College Individual Major",
    "Thurgood Marshall College Individual Studies",
    "Warren College Individual Studies",
    "Sixth College Individual Studies",
    "Seventh College Individual Studies",
    "International Studies — Anthropology",
    "International Studies — Economics",
    "International Studies — History",
    "International Studies — Linguistics",
    "International Studies — Literature",
    "International Studies — Political Science",
    "International Studies — Sociology",
    "International Studies — International Business",
    "International Studies — Philosophy",
    "Italian Studies",
    "Japanese Studies",
    "Jewish Studies",
    "Latin American Studies",
    "Latin American Studies with a Concentration in Mexico",
    "Latin American Studies with a Concentration in Migration and Border Studies",
    "Language Studies",
    "Linguistics",
    "Linguistics (Specialization in Cognition and Language)",
    "Linguistics (Specialization in Language and Society)",
    "Linguistics (Specialization in Speech and Language Sciences)",
    "Literary Arts",
    "Literatures in English",
    "Spanish Literature",
    "World Literature and Culture",
    "Mathematical Biology",
    "Mathematics",
    "Mathematics (Applied)",
    "Mathematics — Applied Science",
    "Mathematics — Computer Science",
    "Mathematics — Secondary Education",
    "Probability & Statistics",
    "Aerospace Engineering",
    "Aerospace Engineering with a Specialization in Aerothermodynamics",
    "Aerospace Engineering with a Specialization in Astrodynamics and Space Applications",
    "Aerospace Engineering with a Specialization in Flight Dynamics and Controls",
    "Mechanical Engineering",
    "Mechanical Engineering with a Specialization in Controls and Robotics",
    "Mechanical Engineering with a Specialization in Fluid Mechanics and Thermal Systems",
    "Mechanical Engineering with a Specialization in Materials Science and Engineering",
    "Mechanical Engineering with a Specialization in Mechanics of Materials",
    "Mechanical Engineering with a Specialization in Renewable Energy and Environmental Flows",
    "Interdisciplinary Computing and the Arts (Music)",
    "Music",
    "Music Humanities",
    "Nanoengineering",
    "Philosophy",
    "General Physics",
    "General Physics/Secondary Education",
    "Physics (B.A.)",
    "Physics (B.S.)",
    "Physics-Biophysics",
    "Physics with a Specialization in Astrophysics",
    "Physics with a Specialization in Computational Physics",
    "Physics with a Specialization in Earth Sciences",
    "Physics with a Specialization in Materials Physics",
    "Political Science",
    "Political Science/American Politics",
    "Political Science/Comparative Politics",
    "Political Science/International Relations",
    "Political Science/Political Theory",
    "Political Science/Public Law",
    "Political Science/Public Policy",
    "Political Science/Data Analytics",
    "Political Science/International Affairs",
    "Political Science/Race, Ethnicity, and Politics",
    "Psychology (B.A.)",
    "Psychology (B.S.)",
    "Psychology with a Specialization in Clinical Psychology",
    "Psychology with a Specialization in Cognitive Psychology",
    "Psychology with a Specialization in Developmental Psychology",
    "Psychology with a Specialization in Human Health",
    "Psychology with a Specialization in Sensation and Perception",
    "Psychology with a Specialization in Social Psychology",
    "Cognitive and Behavioral Neuroscience",
    "Business Psychology",
    "Study of Religion",
    "Russian, East European, and Eurasian Studies",
    "Marine Biology",
    "Oceanic and Atmospheric Sciences",
    "Geosciences",
    "Sociology",
    "Sociology-American Studies",
    "Sociology-Culture and Communication",
    "Sociology-Economy and Society",
    "Sociology-International Studies",
    "Sociology-Law and Society",
    "Sociology-Science and Medicine",
    "Sociology-Social Inequality",
    "Structural Engineering",
    "Structural Engineering with a Specialization in Aerospace Structures",
    "Structural Engineering with a Specialization in Civil Structures",
    "Structural Engineering with a Specialization in Geotechnical Engineering",
    "Structural Engineering with a Specialization in Structural Health Monitoring/Non-Destructive Evaluation",
    "Dance",
    "Theatre",
    "Undeclared",
    "Undeclared — Humanities/Arts",
    "Undeclared — Physical Sciences",
    "Undeclared — Social Sciences",
    "Urban Studies and Planning",
    "Real Estate and Development",
    "Interdisciplinary Computing and the Arts (Visual Arts)",
    "Visual Arts (Art History/Criticism)",
    "Visual Arts (Media)",
    "Visual Arts (Studio)",
    "Speculative Design",
]